// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type File struct {
	ID          interface{}
	ProjectID   interface{}
	UserID      interface{}
	Name        string
	Path        string
	Size        int64
	Mode        string
	Modtime     time.Time
	Sha512      string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Project struct {
	ID          interface{}
	Name        string
	Path        string
	Description sql.NullString
	CreatedBy   interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeleteAt    sql.NullTime
}

type User struct {
	ID        interface{}
	Uid       int64
	Username  string
	Fullname  string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
